version: "3.5"
services:
  crawler:
    build: .
    env_file: env
    volumes:
    - ./crawler/:/app/
  selenium-server:
    image: selenium/standalone-chrome-debug
    ports:
    - 5900:5900
  db:
    image: mysql:5
    env_file: env
    volumes:
    - ./db/:/var/lib/mysql/
